---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: jenkins-master

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
    - name: slaves
      port: 50000
      targetPort: 50000
      protocol: TCP
  selector:
    name: jenkins-master

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rbac
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-role
subjects:
- kind: ServiceAccount
  name: jenkins-sa

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jcasc
  namespace: jenkins
data:
  casc.yml: |
    jenkins:
      systemMessage: "V5: Stateless Jenkins w/ JCasC!!!"
      labelString: jenkins-master
      quietPeriod: 2
      mode: EXCLUSIVE
      numExecutors: 1
      crumbIssuer: standard
      remotingSecurity:
        enabled: true
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: admin
              password: root
            - id: doge
              password: wow
      authorizationStrategy:
        globalMatrix:
          grantedPermissions:
            - "Overall/Read:authenticated"
            - "Job/Read:authenticated"
            - "View/Read:authenticated"
            - "Overall/Administer:admin"
      clouds:
        - kubernetes:
            name: kubernetes
            namespace: jenkins
            skipTlsVerify: true
            serverUrl: https://kubernetes.default.svc.cluster.local
            jenkinsUrl: http://jenkins-ui.jenkins.svc.cluster.local:8080
            jenkinsTunnel: jenkins-discovery.jenkins.svc.cluster.local:50000
            containerCapStr: 10
            templates:
              - name: jenkins-slave
                namespace: jenkins
                label: jenkins-slave
                containers:
                  - name: jenkins-slave
                    image: jenkinsci/jnlp-slave:latest
                    workingDir: "/home/jenkins"
                    ttyEnabled: true
                    command: "/bin/sh -c"
                    args: "cat"
                nodeUsageMode: NORMAL
    security:
      remotingCLI:
        enabled: false
    unclassified:
      location:
        url: http://192.168.99.100:30123/
    tool:
      git:
        installations:
        - home: "git"
          name: "Default"
    jobs:
      - script: >
          pipelineJob('CasC - DSL Scripted 0') {
            definition {
              cps {
                script('''
          properties([parameters([booleanParam(defaultValue: false, description: '', name: 'isRelease')])])

          node('jenkins-slave') {
            stage("checkout") {
              echo "Checking out..."
            }

            stage("build") {
              echo "Building..."
              sleep 2
            }

            stage("release") {
              if(!params?.isRelease) {
                echo "Release build is not enabled"
              } else {
                echo "Release build enabled. Running release."
                sleep 15
              }
            }
          }
                ''')
                sandbox()
              }
            }
          }
      - script: >
          pipelineJob('CasC - DSL Scripted 1') {
            definition {
              cps {
                script('''
          node('jenkins-slave') {
            stage("checkout") {
              echo "Checking out..."
            }

            stage("build") {
              echo "Building..."
              sleep 2
            }

            stage("release") {
              echo "Release build enabled. Running release."
              sleep 15
            }
          }
                ''')
                sandbox()
              }
            }
          }
      - script: >
          pipelineJob('CasC - DSL Declarative 0') {
            definition {
              cps {
                script('''
          pipeline {
            agent {
              label 'jenkins-slave'
            }
            options {
              timeout(time: 30, unit: 'MINUTES')
              timestamps()
            }
            stages {
              stage ('build') {
                steps {
                  sh "sleep 2"
                }
              }
              stage ('deploy:prod') {
                steps {
                  sh"sleep 15"
                }
              }
            }
          }
                ''')
                sandbox()
              }
            }
          }
      - script: >
          pipelineJob('spotify-luigi') {
            displayName("spotify-luigi")
            description("Build environment for Spotify's Luigi")
            logRotator {
              numToKeep(5)
            }
            parameters {
              choiceParam('SleepTime', [0, 1, 5, 10])
            }
            properties {
              githubProjectUrl('https://github.com/spotify/luigi.git')
            }
            definition {
              cps {
                script('''
          pipeline {
            agent {
              label 'jenkins-master'
            }
            options {
              timeout(time: 30, unit: 'MINUTES')
              timestamps()
            }
            stages {
              stage ('checkout') {
                steps {
                  git url: 'https://github.com/spotify/luigi.git', branch: 'master'
                }
              }
              stage ('build') {
                steps {
                  sh """
                    python -m virtualenv ~/venv
                    ~/venv/bin/pip install tox
                  """
                }
              }
              stage ('test-docs') {
                steps {
                  sh """
                    ~/venv/bin/tox -e docs
                  """
                }
              }
              stage ('test-flake8') {
                steps {
                  sh """
                    ~/venv/bin/tox -e flake8
                  """
                }
              }
              stage ('sleep') {
                steps {
                  sleep params?.SleepTime
                }
              }
            }
          }
                ''')
                sandbox()
              }
            }
          }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins-master
      labels:
        name: jenkins-master
    spec:
      serviceAccountName: jenkins-sa
      containers:
        - name: jenkins-master
          image: ds/jenkins-v5:2.147
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false -Dhudson.slaves.NodeProvisioner.initialDelay=0
            - name: CASC_JENKINS_CONFIG
              # https://github.com/jenkinsci/configuration-as-code-plugin/issues/425
              value: /var/jenkins_config/..data/casc.yml
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-casc
              mountPath: /var/jenkins_config
      volumes:
        - name: jenkins-home
          emptyDir: {}
        - name: jenkins-casc
          configMap:
            name: jcasc
