jenkins:
  systemMessage: "Stateless Jenkins w/ JCasC!"
  labelString: "jenkins-master"
  mode: EXCLUSIVE
  numExecutors: 3
  crumbIssuer: "standard"
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: root
        - id: doge
          password: wow
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:authenticated"
        - "Job/Read:authenticated"
        - "View/Read:authenticated"
        - "Overall/Administer:admin"
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://192.168.99.100:8443/"
        jenkinsUrl: "http://172.17.0.6:8080/"
        templates:
          - name: "jenkins-slave"
            label: "jenkins-slave"
            containers:
              - name: "jenkins-slave"
                image: "jenkinsci/jnlp-slave:latest"
                workingDir: "/home/jenkins"
                ttyEnabled: true
                command: "/bin/sh -c"
                args: "cat"
            nodeUsageMode: "NORMAL"
security:
  remotingCLI:
    enabled: false
unclassified:
  location:
    url: http://192.168.99.100:30123/
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
  - script: >
      pipelineJob('CasC - DSL Scripted') {
        definition {
          cps {
            script('''
      properties([parameters([booleanParam(defaultValue: false, description: '', name: 'isRelease')])])

      node("jenkins-master") {
        stage("checkout") {
          echo "Checking out..."
        }

        stage("build") {
          echo "Building..."
          sleep 2
        }

        stage("changelog") {
          pac()
        }

        stage("release") {
          if(!params?.isRelease) {
            echo "Release build is not enabled"
          } else {
            echo "Release build enabled. Running release."
            sleep 15
          }
        }
      }
            ''')
            sandbox()
          }
        }
      }
  - script: >
    projectName = "CasC - DSL Declaritive"

    job("Checkout") {
      description "Checking out code"
    }
    job("Build") {
      description "Building code"
      steps {
        sh "sleep 2"
      }
    }
    job("Changelog") {
      pac()
    }
    job("Release") {
      description "Releasing"
      sh "sleep 15"
    }
