---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30123
      protocol: TCP
  selector:
    name: jenkins-master

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
  namespace: jenkins
spec:
  type: ClusterIP
  ports:
    - name: slaves
      port: 50000
      targetPort: 50000
      protocol: TCP
  selector:
    name: jenkins-master

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rbac
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-role
subjects:
- kind: ServiceAccount
  name: jenkins-sa

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jcasc
  namespace: jenkins
data:
  casc.yml: |
    jenkins:
      systemMessage: "V3: Stateless Jenkins w/ JCasC!!!"
      labelString: jenkins-master
      quietPeriod: 2
      mode: EXCLUSIVE
      numExecutors: 0
      crumbIssuer: standard
      remotingSecurity:
        enabled: true
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: admin
              password: root
            - id: doge
              password: wow
      authorizationStrategy:
        globalMatrix:
          grantedPermissions:
            - "Overall/Read:authenticated"
            - "Job/Read:authenticated"
            - "View/Read:authenticated"
            - "Overall/Administer:admin"
      clouds:
        - kubernetes:
            name: kubernetes
            namespace: jenkins
            skipTlsVerify: true
            serverUrl: https://kubernetes.default
            jenkinsUrl: http://jenkins-ui.jenkins:8080
            jenkinsTunnel: jenkins-discovery.jenkins:50000
            containerCapStr: 10
            templates:
              - name: jenkins-slave
                namespace: jenkins
                label: jenkins-slave
                containers:
                  - name: jenkins-slave
                    image: jenkinsci/jnlp-slave:latest
                    workingDir: "/home/jenkins"
                    ttyEnabled: true
                    command: "/bin/sh -c"
                    args: "cat"
                nodeUsageMode: NORMAL
    security:
      remotingCLI:
        enabled: false
    unclassified:
      location:
        url: http://192.168.99.100:30123/
    tool:
      git:
        installations:
        - home: "git"
          name: "Default"
    jobs:
      - script: >
          pipelineJob('CasC - DSL Scripted') {
            definition {
              cps {
                script('''
          properties([parameters([booleanParam(defaultValue: false, description: '', name: 'isRelease')])])

          node() {
            stage("checkout") {
              echo "Checking out..."
            }

            stage("build") {
              echo "Building..."
              sleep 2
            }

            stage("release") {
              if(!params?.isRelease) {
                echo "Release build is not enabled"
              } else {
                echo "Release build enabled. Running release."
                sleep 15
              }
            }
          }
                ''')
                sandbox()
              }
            }
          }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins-master
      labels:
        name: jenkins-master
    spec:
      serviceAccountName: jenkins-sa
      containers:
        - name: jenkins-master
          image: ds/jenkins-v4:2.146
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false -Dhudson.slaves.NodeProvisioner.initialDelay=0
            - name: CASC_JENKINS_CONFIG
              # https://github.com/jenkinsci/configuration-as-code-plugin/issues/425
              value: /var/jenkins_config/..data/casc.yml
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-casc
              mountPath: /var/jenkins_config
          # livenessProbe:
          #   httpGet:
          #     path: /login
          #     port: 8080
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /login
          #     port: 8080
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 5
      volumes:
        - name: jenkins-home
          emptyDir: {}
        - name: jenkins-casc
          configMap:
            name: jcasc
